notes: |
  Toont een dropdown met daarin een gevulde uitklapper. Gebaseerd op de Bootstrap "Dropdowns" component
status: ready
context:
  id: actie
  label: Actie
  items:
    -
      - Actie
      - Andere actie
      - Nog iets anders hier
    -
      - Gescheiden link
