# based on https://raw.githubusercontent.com/sasstools/sass-lint/master/lib/config/sass-lint.yml
# see https://github.com/sasstools/sass-lint/tree/master/docs/rules
# 0 = disabled, 1 = warning, 2 = error

options:
  formatter: stylish

rules:
  # Extends
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 0

  # Mixins
  mixins-before-declarations: 2

  # Line Spacing
  one-declaration-per-line: 2
  empty-line-between-blocks:
    - 2
    -
      include: true
      allow-single-line-rulesets: false
  single-line-per-selector: 2

  # Disallows
  no-attribute-selectors: 0
  no-color-hex: 0
  no-color-keywords: 2
  no-color-literals: 1
  no-combinators: 0
  no-css-comments: 2
  no-debug: 2
  no-disallowed-properties: 0
  no-duplicate-properties: 1
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 1
  no-important: 0
  no-invalid-hex: 2
  no-mergeable-selectors: 0
  no-misspelled-properties: 2
  no-qualifying-elements:
    - 1
    -
      allow-element-with-attribute: true
      allow-element-with-class: true
      allow-element-with-id: false
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  no-transition-all: 0
  no-universal-selectors: 0
  no-url-domains: 2
  no-url-protocols:
    - 2
    -
      allow-protocol-relative-urls: true
  no-vendor-prefixes: 2
  no-warn: 1
  property-units: 1

  # Nesting
  declarations-before-nesting: 2
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0

  # Name Formats
  class-name-format:
    - 1
    -
      allow-leading-underscore: false
      convention: hyphenatedlowercase
  function-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: hyphenatedlowercase
  id-name-format:
    - 1
    -
      allow-leading-underscore: false
      convention: hyphenatedlowercase
  mixin-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: hyphenatedlowercase
  placeholder-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: hyphenatedlowercase
  variable-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: hyphenatedlowercase
  # Style Guide
  attribute-quotes: 2
  bem-depth:
    - 2
    -
      max-depth: 4
  border-zero: 2
  brace-style:
    - 2
    -
      style: stroustrup
      allow-single-line: false
  clean-import-paths:
    - 2
    -
      leading-underscore: false
      filename-extension: false
  empty-args: 2
  hex-length:
    - 2
    -
      style: short
  hex-notation:
    - 2
    -
      style: lowercase
  indentation:
    - 2
    -
      size: 2
  leading-zero:
    - 2
    -
      include: false
  max-line-length:
    - 1
    -
      length: 160
  max-file-line-count:
    - 1
    -
      length: 300
  nesting-depth:
    - 2
    -
      max-depth: 5
  property-sort-order:
    - 2
    -
      order: alphabetical
      ignore-custom-properties: false
  pseudo-element: 2
  quotes:
    - 2
    -
      style: double
  shorthand-values:
    - 2
    -
      allowed-shorthands: [1, 2, 3]
  url-quotes: 2
  variable-for-property: 0
  zero-unit: 2

  # Inner Spacing
  space-after-comma: 2
  space-before-colon: 2
  space-after-colon: 2
  space-before-brace: 2
  space-before-bang: 2
  space-after-bang: 2
  space-between-parens: 2
  space-around-operator: 2

  # Final Items
  trailing-semicolon: 2
  final-newline: 2
