status: ready
context:
  id: beleg
  type: select
  label: Beleg
  multiple: true
  helpText: Deze producten worden allemaal gemaakt in een fabriek waar ook noten worden verwerkt
  options:
    - optionType: Vlees
      items:
        - value: worst
          label: Worst
        - value: salami
          label: Salami
        - value: geit
          label: Geit
    - optionType: Vis
      items:
        - value: zalm
          label: Zalm
        - value: makreel
          label: Makreel
