status: inprogress
collated: true
context:
  label: Hergebruiken
  position: top
variants:
  - name: tooltip-long-text
    context:
      label: Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.
  - name: tooltip-left
    context:
      label: Ik sta links van de content.
      position: left
  - name: tooltip-right
    context:
      label: Ik sta rechts van de content.
      position: right
  - name: tooltip-bottom
    context:
      label: Ik sta onder de content.
      position: bottom
