status: ready
context:
  items:
    - label: Locatie bepalen
      state: done
    - label: Werkzaamheden kiezen
      state: active
    - label: Werkzaamheden checken
      state: next
    - label: Resultaat
      state: disabled
