describe("Progress Indicator", () => {
  it("should show spinner", () => {
    cy.visit("http://localhost:45000/iframe.html?id=core-progress-indicator--small")
      .get("dso-progress-indicator")
      .should("have.attr", "size", "small")
      .shadow()
      .as("dsoProgressIndicator")
      .find(".dso-progress-indicator-spinner")
      .should("have.attr", "role", "progressbar")
      .and("have.attr", "aria-labelledby", "progress-indicator-label")
      .and("be.visible")
      .and("have.css", "width", "24px")
      .and("have.css", "height", "24px")
      .get("@dsoProgressIndicator")
      .find(".dso-progress-indicator-label")
      .should("have.text", "Resultaten laden: een moment geduld alstublieft.")
      .get("dso-progress-indicator")
      .invoke("attr", "size", "medium")
      .shadow()
      .find(".dso-progress-indicator-spinner")
      .should("have.attr", "role", "progressbar")
      .and("have.attr", "aria-labelledby", "progress-indicator-label")
      .and("be.visible")
      .and("have.css", "width", "32px")
      .and("have.css", "height", "32px")
      .get("@dsoProgressIndicator")
      .find(".dso-progress-indicator-label")
      .should("have.text", "Resultaten laden: een moment geduld alstublieft.")
      .get("dso-progress-indicator")
      .invoke("attr", "size", "large")
      .shadow()
      .find(".dso-progress-indicator-spinner")
      .should("have.attr", "role", "progressbar")
      .and("have.attr", "aria-labelledby", "progress-indicator-label")
      .and("be.visible")
      .and("have.css", "width", "48px")
      .and("have.css", "height", "48px")
      .get("@dsoProgressIndicator")
      .find(".dso-progress-indicator-label")
      .should("have.text", "Resultaten laden: een moment geduld alstublieft.");
  });
});
