notes: |
  Een help block staat altijd direct in de `.form-group`.
status: ready
context:
  id: select_voorbeeld
  helpText: Selecteer een waarde
  options:
    - optionType: Europees
      items:
        - value: alfa
          label: Alfa Romeo
        - value: fiat
          label: Fiat
        - value: marcedes
          label: Mercedes
          selected: true
        - value: volkswagen
          label: Volkswagen
