notes: De class `cta-primary` en `cta-default` kunnen alleen op elementen van het type `a` of `button` geplaatst worden
status: ready
collated: true
default: button-cta-primary
variants:
  - name: button-cta-primary
    context:
      button: true
      value: Verstuur feedback
      modifier: primary
  - name: button-cta-default
    context:
      button: true
      value: Meld ongewenst gedrag
      modifier: default
  - name: anchor-cta-primary
    context:
      anchor: true
      value: Vraag nu vergunning aan
      modifier: primary
      url: "#"
  - name: anchor-cta-default
    context:
      anchor: true
      value: E-mail de redactie
      modifier: default
      url: "#"