status: ready
collated: true
context:
  label: Versturen
  type: button
  modifier: default
variants:
  - name: default
    label: Default button
  - name: primary
    label: Primary submit button
    context:
      type: submit
      modifier: primary
  - name: disabled
    label: Disabled button
    context:
      type: submit
      modifier: default
      disabled: true
  - name: with-icon
    label: Default button with icon
    context:
      icon: fa fa-lock
      iconOnly: true
      label: Vergrendelen
  - name: with-badge
    label: Primary button with badge
    context:
      count: 3
  - name: with-icon-badge
    label: Button with icon and badge
    context:
      icon: fa fa-envelope-o
      label: Berichten
      count: 3
